/** Every string of the settings, in each interface language. */
export const SETTINGS_TEXT = {
  ru: {
    title: 'Настройки',
    subtitle: 'Профиль, вход, тема и звук',
    tabs: { profile: 'Профиль', general: 'Общие', account: 'Аккаунт' },
    close: 'Закрыть',
    member: 'Аккаунт',
    guestBadge: 'Гость',

    avatar: 'Аватар',
    upload: 'Загрузить',
    uploadPhoto: 'Загрузить фото',
    myAvatars: 'Мои загрузки',
    basicAvatars: 'Коллекция',
    nickname: 'Имя пользователя',
    save: 'Сохранить',
    nameTaken: 'Это имя уже занято',
    nameShort: 'Имя — от 2 символов',
    saveError: 'Не удалось сохранить',
    fileTooLarge: 'Файл больше 2 МБ',
    deleteAvatar: 'Удалить аватар',
    deleteConfirmTitle: 'Удалить аватар?',
    deleteConfirmDesc: 'Это действие нельзя отменить.',
    cancel: 'Отмена',
    confirmDelete: 'Удалить',

    theme: 'Тема',
    themeLight: 'Светлая',
    themeDark: 'Тёмная',
    themeSystem: 'Авто',
    lang: 'Язык',
    sound: 'Звук',
    effects: 'Эффекты',
    music: 'Музыка в Songler',
    mute: 'Выключить звук',
    unmute: 'Включить звук',
    notifications: 'Уведомления',
    alertsTitle: 'Звать в игру',
    alertsDesc: 'Когда ваш ход или игра началась, а вкладка свёрнута, — мигает заголовок и звучит сигнал',
    notifyTitle: 'Системные уведомления',
    notifyDesc: 'Всплывающее уведомление поверх других окон',
    notifyBlocked: 'Запрещены в настройках браузера',
    chat: 'Чат',
    chatTitle: 'Чат в комнатах',
    chatDesc: 'Кнопка чата в лобби и во время игры',

    signIn: 'Вход',
    methodEmail: 'Почта и пароль',
    methodGoogle: 'Google',
    email: 'Почта',
    change: 'Изменить',
    newEmail: 'Новая почта',
    send: 'Отправить',
    emailChangeSent: 'Подтвердите смену по ссылкам в письмах — на старый и на новый адрес',
    pendingEmail: 'Ждёт подтверждения:',
    changePass: 'Пароль',
    passDesc: 'Пришлём на почту ссылку, чтобы задать новый пароль.',
    sendReset: 'Отправить ссылку',
    resetSent: 'Проверьте почту',
    wait: 'Ждите',
    sec: 'с',
    setPassTitle: 'Задайте пароль',
    setPassDesc: 'Почта подтверждена — придумайте пароль, чтобы входить по имени или почте.',
    newPassword: 'Новый пароль',
    setPass: 'Сохранить пароль',
    passSaved: 'Пароль сохранён',
    shortPassword: 'Пароль — не короче 6 символов',
    showPassword: 'Показать пароль',
    hidePassword: 'Скрыть пароль',
    logout: 'Выйти из аккаунта',

    keepTitle: 'Сохраните прогресс',
    keepDesc: 'Привяжите почту или Google — статистика, достижения и аватарки останутся с вами. Гостевой профиль, в который не заходили 30 дней, удаляется.',
    keepButton: 'Привязать почту',
    keepSent: (email: string) => `Письмо отправлено на ${email}. Перейдите по ссылке — и профиль станет постоянным.`,
    or: 'или',
    linkGoogle: 'Привязать Google',
    linkUnavailable: 'Привязка Google пока недоступна',
    emailTaken: 'Эта почта уже зарегистрирована — войдите в тот аккаунт',
    identityTaken: 'Этот Google-аккаунт уже привязан к другому профилю',

    danger: 'Удаление',
    deleteAccount: 'Удалить аккаунт',
    deleteGuest: 'Удалить гостевой профиль',
    deleteAccountDesc: 'Профиль, статистика, история матчей, достижения, загруженные аватарки и ваши комнаты удалятся навсегда.',
    deleteConfirm: 'Удалить аккаунт навсегда?',
    typeName: 'Чтобы подтвердить, введите своё имя:',
    deleteForever: 'Удалить навсегда',
    deleteFailed: 'Не удалось удалить аккаунт',
  },
  en: {
    title: 'Settings',
    subtitle: 'Profile, sign-in, theme and sound',
    tabs: { profile: 'Profile', general: 'General', account: 'Account' },
    close: 'Close',
    member: 'Account',
    guestBadge: 'Guest',

    avatar: 'Avatar',
    upload: 'Upload',
    uploadPhoto: 'Upload a photo',
    myAvatars: 'My uploads',
    basicAvatars: 'Collection',
    nickname: 'Username',
    save: 'Save',
    nameTaken: 'This name is taken',
    nameShort: 'At least 2 characters',
    saveError: 'Could not save',
    fileTooLarge: 'The file is larger than 2 MB',
    deleteAvatar: 'Delete avatar',
    deleteConfirmTitle: 'Delete avatar?',
    deleteConfirmDesc: 'This action cannot be undone.',
    cancel: 'Cancel',
    confirmDelete: 'Delete',

    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'Auto',
    lang: 'Language',
    sound: 'Sound',
    effects: 'Effects',
    music: 'Music in Songler',
    mute: 'Mute',
    unmute: 'Unmute',
    notifications: 'Notifications',
    alertsTitle: 'Call me back to the game',
    alertsDesc: 'When it is your turn or a match starts while the tab is hidden, the title flashes and a chime plays',
    notifyTitle: 'System notifications',
    notifyDesc: 'A pop-up on top of other windows',
    notifyBlocked: 'Blocked in the browser settings',
    chat: 'Chat',
    chatTitle: 'Room chat',
    chatDesc: 'The chat button in the lobby and during a match',

    signIn: 'Sign-in',
    methodEmail: 'Email and password',
    methodGoogle: 'Google',
    email: 'Email',
    change: 'Change',
    newEmail: 'New email',
    send: 'Send',
    emailChangeSent: 'Confirm the change with the links sent to both your old and new address',
    pendingEmail: 'Waiting for confirmation:',
    changePass: 'Password',
    passDesc: 'We will email you a link to set a new password.',
    sendReset: 'Send link',
    resetSent: 'Check your email',
    wait: 'Wait',
    sec: 's',
    setPassTitle: 'Set a password',
    setPassDesc: 'Your email is confirmed — choose a password to sign in by username or email.',
    newPassword: 'New password',
    setPass: 'Save password',
    passSaved: 'Password saved',
    shortPassword: 'The password needs at least 6 characters',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    logout: 'Sign out',

    keepTitle: 'Keep your progress',
    keepDesc: 'Add an email or Google — your stats, achievements and avatars stay with you. A guest profile not opened for 30 days is deleted.',
    keepButton: 'Add email',
    keepSent: (email: string) => `We sent a message to ${email}. Follow the link and the profile becomes permanent.`,
    or: 'or',
    linkGoogle: 'Link Google',
    linkUnavailable: 'Linking Google is not available yet',
    emailTaken: 'This email is already registered — sign in to that account',
    identityTaken: 'This Google account is already linked to another profile',

    danger: 'Delete',
    deleteAccount: 'Delete account',
    deleteGuest: 'Delete guest profile',
    deleteAccountDesc: 'Your profile, stats, match history, achievements, uploaded avatars and your rooms are deleted for good.',
    deleteConfirm: 'Delete the account for good?',
    typeName: 'To confirm, type your name:',
    deleteForever: 'Delete for good',
    deleteFailed: 'Could not delete the account',
  },
  uk: {
    title: 'Налаштування',
    subtitle: 'Профіль, вхід, тема і звук',
    tabs: { profile: 'Профіль', general: 'Загальні', account: 'Акаунт' },
    close: 'Закрити',
    member: 'Акаунт',
    guestBadge: 'Гість',

    avatar: 'Аватар',
    upload: 'Завантажити',
    uploadPhoto: 'Завантажити фото',
    myAvatars: 'Мої завантаження',
    basicAvatars: 'Колекція',
    nickname: 'Ім’я користувача',
    save: 'Зберегти',
    nameTaken: 'Це ім’я вже зайняте',
    nameShort: 'Ім’я — від 2 символів',
    saveError: 'Не вдалося зберегти',
    fileTooLarge: 'Файл більший за 2 МБ',
    deleteAvatar: 'Видалити аватар',
    deleteConfirmTitle: 'Видалити аватар?',
    deleteConfirmDesc: 'Цю дію не можна скасувати.',
    cancel: 'Скасувати',
    confirmDelete: 'Видалити',

    theme: 'Тема',
    themeLight: 'Світла',
    themeDark: 'Темна',
    themeSystem: 'Авто',
    lang: 'Мова',
    sound: 'Звук',
    effects: 'Ефекти',
    music: 'Музика в Songler',
    mute: 'Вимкнути звук',
    unmute: 'Увімкнути звук',
    notifications: 'Сповіщення',
    alertsTitle: 'Кликати в гру',
    alertsDesc: 'Коли ваш хід або гра почалася, а вкладку згорнуто, — блимає заголовок і лунає сигнал',
    notifyTitle: 'Системні сповіщення',
    notifyDesc: 'Спливне сповіщення поверх інших вікон',
    notifyBlocked: 'Заборонені в налаштуваннях браузера',
    chat: 'Чат',
    chatTitle: 'Чат у кімнатах',
    chatDesc: 'Кнопка чату в лобі та під час гри',

    signIn: 'Вхід',
    methodEmail: 'Пошта й пароль',
    methodGoogle: 'Google',
    email: 'Пошта',
    change: 'Змінити',
    newEmail: 'Нова пошта',
    send: 'Надіслати',
    emailChangeSent: 'Підтвердьте зміну за посиланнями в листах — на стару й на нову адресу',
    pendingEmail: 'Чекає на підтвердження:',
    changePass: 'Пароль',
    passDesc: 'Надішлемо на пошту посилання, щоб задати новий пароль.',
    sendReset: 'Надіслати посилання',
    resetSent: 'Перевірте пошту',
    wait: 'Зачекайте',
    sec: 'с',
    setPassTitle: 'Задайте пароль',
    setPassDesc: 'Пошту підтверджено — придумайте пароль, щоб входити за ім’ям або поштою.',
    newPassword: 'Новий пароль',
    setPass: 'Зберегти пароль',
    passSaved: 'Пароль збережено',
    shortPassword: 'Пароль — не коротший за 6 символів',
    showPassword: 'Показати пароль',
    hidePassword: 'Сховати пароль',
    logout: 'Вийти з акаунта',

    keepTitle: 'Збережіть прогрес',
    keepDesc: 'Прив’яжіть пошту або Google — статистика, досягнення й аватарки залишаться з вами. Гостьовий профіль, у який не заходили 30 днів, видаляється.',
    keepButton: 'Прив’язати пошту',
    keepSent: (email: string) => `Лист надіслано на ${email}. Перейдіть за посиланням — і профіль стане постійним.`,
    or: 'або',
    linkGoogle: 'Прив’язати Google',
    linkUnavailable: 'Прив’язка Google поки недоступна',
    emailTaken: 'Ця пошта вже зареєстрована — увійдіть у той акаунт',
    identityTaken: 'Цей Google-акаунт уже прив’язаний до іншого профілю',

    danger: 'Видалення',
    deleteAccount: 'Видалити акаунт',
    deleteGuest: 'Видалити гостьовий профіль',
    deleteAccountDesc: 'Профіль, статистика, історія матчів, досягнення, завантажені аватарки та ваші кімнати буде видалено назавжди.',
    deleteConfirm: 'Видалити акаунт назавжди?',
    typeName: 'Щоб підтвердити, введіть своє ім’я:',
    deleteForever: 'Видалити назавжди',
    deleteFailed: 'Не вдалося видалити акаунт',
  },
};

export type SettingsText = typeof SETTINGS_TEXT.en;
